In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\CLASSIC\OneDrive\Documents\jupyter x\Datasets\Titanic-Dataset.CSV", encoding='ISO-8859-1')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [6]:
print("--- DATA  QUALITY REPORT ---")
print("Shape:", df.shape)
print("\n--- Nulls per colum---")
print(df.isnull().sum())
print("\n---Duplicates ---")
print(df.duplicated().sum()) 
print("\n---Data types ---")
print(df.dtypes)

--- DATA  QUALITY REPORT ---
Shape: (891, 12)

--- Nulls per colum---
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

---Duplicates ---
0

---Data types ---
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df.drop(columns=['Cabin'], inplace=True)

df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [16]:
print("Before:", df.shape[0])
df.drop_duplicates(inplace=True)
print("After:", df.shape[0])
print("Duplicates removed:", df.duplicated().sum())

Before: 891
After: 891
Duplicates removed: 0

In [17]:
df['Sex'] = df['Sex'].str.lower().str.strip()
df['Embarked'] = df['Embarked'].str.strip()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [25]:
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5*IQR
Upper = Q3 + 1.5*IQR

outliers = df[(df['Fare'] < lower) | (df['Fare'] > Upper)]
print("Outliers in Fare:", len(outliers))
print(f"Decision: Retain outliers - they are valid expensive tickets")

Outliers in Fare: 116
Decision: Retain outliers - they are valid expensive tickets

In [27]:
df['Pclass'] = df['Pclass'].astype(str)
df.to_csv("Titanic_cleaned.csv", index=False)
print("Cleaned file saved!")

Cleaned file saved!

In [33]:
print("=== BEFORE CLEANING ===")
print("Rows: 891")
print("Nulls - Age: 177, Cabin: 687, Embarked: 2")
print("Duplicates: 0")
print("Data types had issues - pclass was int. should be string")

print("\n=== AFTER CLEANING ===")
print("Rows:", df.shape[0])
print("Nulls:")
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())
print("\nData types after:")
print(df.dtypes)

print("\n=== JUSTIFICATIONS ===")
print("Cabin:Dropped -77% missing, too much")
print("Age: Filled with median - median better than mean for age")
print("Embarked: Filled with mode - most common port")
print("Fare outliers (116): Retained - they are real expensive tickets, not errors")

=== BEFORE CLEANING ===
Rows: 891
Nulls - Age: 177, Cabin: 687, Embarked: 2
Duplicates: 0
Data types had issues - pclass was int. should be string

=== AFTER CLEANING ===
Rows: 891
Nulls:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64
Duplicates: 0

Data types after:
PassengerId      int64
Survived         int64
Pclass          object
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

=== JUSTIFICATIONS ===
Cabin:Dropped -77% missing, too much
Age: Filled with median - median better than mean for age
Embarked: Filled with mode - most common port
Fare outliers (116): Retained - they are real expensive tickets, not errors